apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: golang-apps
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: golang-apps
    spec:
      containers:
        - name: golang-apps
          image: index.docker.io/reja13/golang-testing:v2
          ports:
            - containerPort: 8000