apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: golang-apps
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: golang-apps
    spec:
      containers:
        - name: golang-apps
          image: registry.micro.uii.id/uii-gateway-golang/golang-testing-automation/golang-testing:v1
      imagePullSecrets:
        - name: registry-secret